config/routes.rb
Rails.application.routes.draw do
  resources :sneakers do
    resources :reviews
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root 'sneakers#index'

  scope '/cart/:sneaker_id' do
    post 'add', to: 'line_items#update', as: 'add_to_cart'
    delete 'remove', to: 'line_items#destroy', as: 'remove_from_cart'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :line_items, dependent: :destroy

  def add_sneaker(sneaker)
    item = find_item(sneaker)
    if item
      item.increment(:quantity)
    else
      item = line_items.build(sneaker_id: sneaker.id, quantity: 1)
    end
    item
  end

  def remove_sneaker(sneaker)
    item = find_item(sneaker.id)
    return unless item

    item.decrement(:quantity) if item.quantity > 0

    item.destroy if item.quantity.zero?
    item
  end

  def total_price
    line_items.to_a.sum(&:total_price)
  end

  def sneaker_count(sneaker)
    find_item(sneaker.id)&.quantity || 0
  end

  private

  def find_item(sneaker_id)
    line_items.find_by(sneaker_id:)
  end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :sneaker
  belongs_to :cart

  def total_price
    sneaker.price * quantity
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :sneaker

  validates :body, presence: true, length: { minimum: 6 }
  validates :rating, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }
end

app/models/sneaker.rb
class Sneaker < ApplicationRecord
  has_one_attached :image

  has_many :line_items, dependent: :destroy
  has_many :reviews, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User

  has_one :cart
  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
end

app/controllers/authed_controller.rb
class AuthedController < ApplicationController
  before_action :require_login
  before_action :set_cart

  def set_cart
    @cart = Cart.find_or_create_by(user_id: current_user.id)
  end
end

app/controllers/carts_controller.rb
class CartsController < AuthedController
end

app/controllers/line_items_controller.rb
class LineItemsController < AuthedController
  before_action :set_sneaker

  def update
    item = @cart.add_sneaker(@sneaker)
    item.save
  end

  def destroy
    item = @cart.remove_sneaker(@sneaker)
    item.save
  end

  private

  def set_sneaker
    @sneaker = Sneaker.find(params[:sneaker_id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < AuthedController
  include ActionView::RecordIdentifier

  before_action :set_review, only: %i[show edit update destroy]
  before_action :set_sneaker

  # GET /reviews or /reviews.json
  def index
    @reviews = @sneaker.reviews
  end

  # GET /reviews/1 or /reviews/1.json
  def show; end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit; end

  # POST /reviews or /reviews.json
  def create
    @review = Review.new(review_params.merge(user: current_user, sneaker: @sneaker))

    respond_to do |format|
      @review.save
      format.turbo_stream
    end
  end

  # PATCH/PUT /reviews/1 or /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to review_url(@review), notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1 or /reviews/1.json
  def destroy
    @review.destroy!

    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_review
    @review = Review.find(params[:id])
  end

  def set_sneaker
    @sneaker = Sneaker.find(params[:sneaker_id])
  end

  # Only allow a list of trusted parameters through.
  def review_params
    params.require(:review).permit(:body, :rating)
  end
end

app/controllers/sneakers_controller.rb
class SneakersController < AuthedController
  before_action :set_sneaker, only: %i[show edit update destroy]

  # GET /sneakers or /sneakers.json
  def index
    @sneakers = Sneaker.all
  end

  # GET /sneakers/1 or /sneakers/1.json
  def show; end

  # GET /sneakers/new
  def new
    @sneaker = Sneaker.new
  end

  # GET /sneakers/1/edit
  def edit; end

  # POST /sneakers or /sneakers.json
  def create
    @sneaker = Sneaker.new(sneaker_params)

    respond_to do |format|
      if @sneaker.save
        format.html { redirect_to sneaker_url(@sneaker), notice: 'Sneaker was successfully created.' }
        format.json { render :show, status: :created, location: @sneaker }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @sneaker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sneakers/1 or /sneakers/1.json
  def update
    respond_to do |format|
      if @sneaker.update(sneaker_params)
        format.html { redirect_to sneaker_url(@sneaker), notice: 'Sneaker was successfully updated.' }
        format.json { render :show, status: :ok, location: @sneaker }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @sneaker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sneakers/1 or /sneakers/1.json
  def destroy
    @sneaker.destroy!

    respond_to do |format|
      format.html { redirect_to sneakers_url, notice: 'Sneaker was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_sneaker
    @sneaker = Sneaker.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def sneaker_params
    params.require(:sneaker).permit(:name, :brand, :description, :price, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_classname(type)
    case type
    when 'notice'
      'bg-blue-500 text-white p-3 rounded'
    when 'success'
      'bg-green-500 text-white p-3 rounded'
    when 'error'
      'bg-red-500 text-white p-3 rounded'
    when 'alert'
      'bg-yellow-500 text-white p-3 rounded'
    else
      'bg-blue-500 text-white p-3 rounded'
    end
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sneakers_helper.rb
module SneakersHelper
end

app/views/carts/_cart.html.erb
<%= turbo_frame_tag dom_id(@cart) do %>
  <details class="relative">
    <summary><%= number_to_currency(@cart.total_price) %></summary>
    <div class="absolute bg-white right-0 w-96 p-2 rounded-b-lg shadow-lg">
      <div class="flex flex-col divide-y divide-gray-100">
        <%= render @cart.line_items %>
      </div>
      <div class="flex px-2 justify-between font-bold border-t-2 border-gray-600">
        <div>Subtotal: </div>
        <div><%= number_to_currency(@cart.total_price) %></div>
      </div>
    </div>
  </details>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sneakerr102</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="h-full antialiased container mx-auto">
    <header class="sticky z-10 flex justify-between px-3 py-5 border-b border-gray-100">
      <h1 class="text-3xl font-bold hover:text-indigo-500">
        <%= link_to "Sneakerr", root_path %>
      </h1>
      <div class="flex gap-5 hover:text-indigo-500">
        <% if signed_in? %>
          <%= render "carts/cart" %>
          <%= button_to 'Sign out', sign_out_path, method: :delete %>
        <% else %>
          <%= link_to 'Sign in', sign_in_path %>
          <%= link_to 'Sign up', sign_up_path %>
        <% end %>
      </div>
    </header>
    <main class="py-5">
      <%= yield %>
    </main>
  </body>
</html>

app/views/line_items/_line_item.html.erb
<div class="flex gap-6 p-3 justify-between">
  <div class="text-sm"><%= line_item.quantity %></div>
  <div class="text-sm"><%= line_item.sneaker.name %></div>
  <div class="text-sm text-green-500 ml-10"><%= line_item.total_price %></div>
</div>

app/views/line_items/destroy.turbo_stream.erb
<%= turbo_stream.update @cart, partial: "carts/cart" %>
<%= turbo_stream.replace dom_id(@sneaker, :items_in_cart), partial: "sneakers/count", locals: {sneaker: @sneaker} %>

app/views/line_items/update.turbo_stream.erb
<%= turbo_stream.update @cart, partial: "carts/cart" %>
<%= turbo_stream.replace dom_id(@sneaker, :items_in_cart), partial: "sneakers/count", locals: {sneaker: @sneaker} %>

app/views/reviews/_form.html.erb
<%= form_with(model: [@sneaker, review], class: "contents") do |form| %>
  <% if review.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
        <% review.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :body %>
    <%= form.text_area :body, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :rating %>
    <%= form.range_field :rating, in: 1..5, step: 1, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/reviews/_review.html.erb
<div id="<%= dom_id review %>" class="space-y-2">
  <p class="font-semibold text-sm">
    <%= review.created_at %>
  </p>

  <p class="text-sm">
    <%= review.body %>
  </p>
</div>

app/views/reviews/create.turbo_stream.erb
<% if @review.persisted? %>
  <%= turbo_stream.update(dom_id(@sneaker, :review_form), partial: 'reviews/review',
                                                                            locals: { review: Review.new }) %>
  <%= turbo_stream.append(dom_id(@sneaker, :reviews),
                                              partial: 'reviews/review', locals: { review: @review }) %>
<% else %>
  <%= turbo_stream.update(dom_id(@sneaker, :review_form), partial: 'reviews/review',
                                                                            locals: { review: @review }) %>
<% end %>

app/views/reviews/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing review</h1>

  <%= render "form", review: @review %>

  <%= link_to "Show this review", @review, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to reviews", reviews_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/reviews/index.html.erb
<%= turbo_frame_tag dom_id(@sneaker, :reviews) do %>
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Reviews</h1>
  </div>

  <div id="reviews" class="min-w-full">
    <%= render @reviews %>
  </div>
</div>
<% end %>

app/views/reviews/new.html.erb
<%= turbo_frame_tag dom_id(@sneaker, :review_form) do %>
<div class="mx-auto md:w-2/3 w-full">

  <%= render "form", review: @review %>
</div>
<% end %>

app/views/reviews/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @review %>

    <%= link_to "Edit this review", edit_review_path(@review), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this review", review_path(@review), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to reviews", reviews_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/shared/_flash.html.erb
<div id="flash">
  <% flash.each do |message_type, message| %>
    <div class="<%= flash_classname(message_type) %>">
      <%= message %>
  <% end %>
</div>

app/views/sneakers/_count.html.erb
<%= turbo_frame_tag dom_id(sneaker, :items_in_cart) do %>
  <div class="absolute flex gap-1 bg-gray-700 text-gray-100 px-3 py-1 right-2 top-2 rounded-full">
    <%= button_to "+", add_to_cart_path(sneaker), class: "font-bold" %>
    <div>
      <%= @cart.sneaker_count(sneaker)  %>
    </div>
    <%= button_to "-", remove_from_cart_path(sneaker), class: "font-bold", method: "delete" %>
  </div>
<% end %>

app/views/sneakers/_form.html.erb
<%= form_with(model: sneaker, class: "contents") do |form| %>
  <% if sneaker.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(sneaker.errors.count, "error") %> prohibited this sneaker from being saved:</h2>

      <ul>
        <% sneaker.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :brand %>
    <%= form.text_field :brand, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :price %>
    <%= form.text_field :price, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :image %>
    <%= form.file_field :image, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/sneakers/_sneaker.html.erb
<div id="<%= dom_id sneaker %>" class="relative shadow-lg rounded-lg border p-2" >

  <div>
    <%= render partial: "count", locals: {sneaker: sneaker} %>
  </div>

  <%= link_to sneaker_path(sneaker) do %>
    <p class="border rounded">
      <%= image_tag sneaker.image %>
    </p>

    <p class="mt-3 font-bold text-sm">
      <%= sneaker.name %>
    </p>

    <p class="my-1 font-semibold text-green-500 text-sm">
      <%= number_to_currency(sneaker.price) %>
    </p>

    <p class="my-1 text-gray-500 text-xs">
      <%= sneaker.brand %>
    </p>

    <p class="my-1 text-gray-700 text-sm">
      <%= sneaker.description %>
    </p>
  <% end %>

  <%= button_to add_to_cart_path(sneaker), class: "btn-primary w-full", method: "post" do %>
    Add to cart
  <% end %>
</div>

app/views/sneakers/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing sneaker</h1>

  <%= render "form", sneaker: @sneaker %>

  <%= link_to "Show this sneaker", @sneaker, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to sneakers", sneakers_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/sneakers/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Sneakers</h1>
    <%= link_to "New sneaker", new_sneaker_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="sneakers" class="mt-10 grid grid-cols-3 gap-10 p-2">
    <%= render @sneakers %>
  </div>
</div>

app/views/sneakers/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New sneaker</h1>

  <%= render "form", sneaker: @sneaker %>

  <%= link_to "Back to sneakers", sneakers_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/sneakers/show.html.erb
<% if notice.present? %>
  <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
<% end %>

<div class="flex">
  <div>
    <%= render @sneaker %>
  </div>
  <div class="w-1/3">
    <%= turbo_frame_tag dom_id(@sneaker, :reviews), src: sneaker_reviews_path(@sneaker)  %>
    <%= turbo_frame_tag dom_id(@sneaker, :review_form), src: new_sneaker_review_path(@sneaker) %>
  </div>
</div>

<%= link_to "Edit this sneaker", edit_sneaker_path(@sneaker), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
<div class="inline-block ml-2">
  <%= button_to "Destroy this sneaker", sneaker_path(@sneaker), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
</div>